version: "3.9"

services:
  database:
    image: postgres
    container_name: lmo-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lmouser
      - POSTGRES_PASSWORD=lensbmensboensb
      - POSTGRES_DB=lmodb
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: lmo-redis
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
