version: "3.9"

services:
  database:
    image: postgres
    container_name: luar-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=luar
      - POSTGRES_DB=luar
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: luar-redis
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
